/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mainPackage;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author avih2
 */
public class RecipeMenu extends javax.swing.JFrame {
    
    private double multiplier;
    ArrayList<JTextField> ingreidentNums = new ArrayList();
    ArrayList<JTextField> ingreidentNames = new ArrayList();
    /**
     * Creates new form RecipeMenu
     */
    public RecipeMenu() {
        initComponents();
        title.setText(MainMenu.getRecipeName());
        ingreidentNums.add(IngredientNum);
        ingreidentNums.add(IngredientNum1);
        ingreidentNums.add(IngredientNum2);
        ingreidentNums.add(IngredientNum3);
        ingreidentNums.add(IngredientNum4);
        ingreidentNums.add(IngredientNum5);
        ingreidentNums.add(IngredientNum6);
        ingreidentNames.add(Ingredient);
        ingreidentNames.add(Ingredient1);
        ingreidentNames.add(Ingredient2);
        ingreidentNames.add(Ingredient3);
        ingreidentNames.add(Ingredient4);
        ingreidentNames.add(Ingredient5);
        ingreidentNames.add(Ingredient6);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        quitButton2 = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        IngredientNum = new javax.swing.JTextField();
        Ingredient = new javax.swing.JTextField();
        IngredientNum1 = new javax.swing.JTextField();
        Ingredient1 = new javax.swing.JTextField();
        IngredientNum2 = new javax.swing.JTextField();
        Ingredient2 = new javax.swing.JTextField();
        IngredientNum3 = new javax.swing.JTextField();
        Ingredient3 = new javax.swing.JTextField();
        IngredientNum4 = new javax.swing.JTextField();
        Ingredient4 = new javax.swing.JTextField();
        Ingredient5 = new javax.swing.JTextField();
        IngredientNum5 = new javax.swing.JTextField();
        IngredientNum6 = new javax.swing.JTextField();
        Ingredient6 = new javax.swing.JTextField();
        multiplierTextField = new javax.swing.JTextField();
        Multipler = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        convertedText = new javax.swing.JTextArea();
        multipleButton = new javax.swing.JButton();
        divideButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        quitButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        quitButton2.setText("RETURN");
        quitButton2.setFocusPainted(false);
        quitButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButton2ActionPerformed(evt);
            }
        });

        title.setFont(new java.awt.Font("Segoe UI Semibold", 1, 48)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("title");
        title.setPreferredSize(new java.awt.Dimension(440, 45));

        IngredientNum.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        IngredientNum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        IngredientNum.setMinimumSize(new java.awt.Dimension(65, 30));
        IngredientNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngredientNumActionPerformed(evt);
            }
        });

        Ingredient.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Ingredient.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Ingredient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngredientActionPerformed(evt);
            }
        });

        IngredientNum1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        IngredientNum1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        IngredientNum1.setMinimumSize(new java.awt.Dimension(65, 30));
        IngredientNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngredientNum1ActionPerformed(evt);
            }
        });

        Ingredient1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Ingredient1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Ingredient1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ingredient1ActionPerformed(evt);
            }
        });

        IngredientNum2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        IngredientNum2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        IngredientNum2.setMinimumSize(new java.awt.Dimension(65, 30));
        IngredientNum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngredientNum2ActionPerformed(evt);
            }
        });

        Ingredient2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Ingredient2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Ingredient2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ingredient2ActionPerformed(evt);
            }
        });

        IngredientNum3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        IngredientNum3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        IngredientNum3.setMinimumSize(new java.awt.Dimension(65, 30));
        IngredientNum3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngredientNum3ActionPerformed(evt);
            }
        });

        Ingredient3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Ingredient3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Ingredient3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ingredient3ActionPerformed(evt);
            }
        });

        IngredientNum4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        IngredientNum4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        IngredientNum4.setMinimumSize(new java.awt.Dimension(65, 30));
        IngredientNum4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngredientNum4ActionPerformed(evt);
            }
        });

        Ingredient4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Ingredient4.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Ingredient4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ingredient4ActionPerformed(evt);
            }
        });

        Ingredient5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Ingredient5.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Ingredient5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ingredient5ActionPerformed(evt);
            }
        });

        IngredientNum5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        IngredientNum5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        IngredientNum5.setMinimumSize(new java.awt.Dimension(65, 30));
        IngredientNum5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngredientNum5ActionPerformed(evt);
            }
        });

        IngredientNum6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        IngredientNum6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        IngredientNum6.setMinimumSize(new java.awt.Dimension(65, 30));
        IngredientNum6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngredientNum6ActionPerformed(evt);
            }
        });

        Ingredient6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Ingredient6.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Ingredient6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ingredient6ActionPerformed(evt);
            }
        });

        multiplierTextField.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        multiplierTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        multiplierTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplierTextFieldActionPerformed(evt);
            }
        });

        Multipler.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Multipler.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Multipler.setText("Multiplier");

        convertedText.setColumns(20);
        convertedText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        convertedText.setRows(5);
        jScrollPane1.setViewportView(convertedText);

        multipleButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        multipleButton.setText("Multiply");
        multipleButton.setFocusPainted(false);
        multipleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multipleButtonActionPerformed(evt);
            }
        });

        divideButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        divideButton.setText("Divide");
        divideButton.setFocusPainted(false);
        divideButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideButtonActionPerformed(evt);
            }
        });

        clearButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        clearButton.setText("CLEAR");
        clearButton.setFocusPainted(false);
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(quitButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IngredientNum5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IngredientNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IngredientNum3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IngredientNum4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IngredientNum6, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IngredientNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IngredientNum, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Ingredient5, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ingredient2, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ingredient4, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ingredient3, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ingredient6, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ingredient1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ingredient, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(Multipler, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(130, 130, 130)
                                        .addComponent(multiplierTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(124, 124, 124)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(multipleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(divideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGap(561, 561, 561)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(Multipler)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(multiplierTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IngredientNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ingredient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IngredientNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ingredient1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IngredientNum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ingredient2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(multipleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IngredientNum3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ingredient3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IngredientNum4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ingredient4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(divideButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IngredientNum5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ingredient5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IngredientNum6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ingredient6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 182, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(quitButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void quitButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButton2ActionPerformed
        // TODO add your handling code here:
        JFrame quitConfirm = new JFrame();
        if(JOptionPane.showConfirmDialog(quitConfirm, "Are you sure you want to return to menu. Your recipe will not be saved", "QUIT", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            close();
            MainMenu menu = new MainMenu();
            menu.setVisible(true);
        }
    }//GEN-LAST:event_quitButton2ActionPerformed

    private void IngredientNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngredientNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngredientNumActionPerformed

    private void IngredientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngredientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngredientActionPerformed

    private void IngredientNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngredientNum1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngredientNum1ActionPerformed

    private void Ingredient1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ingredient1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ingredient1ActionPerformed

    private void IngredientNum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngredientNum2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngredientNum2ActionPerformed

    private void Ingredient2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ingredient2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ingredient2ActionPerformed

    private void IngredientNum3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngredientNum3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngredientNum3ActionPerformed

    private void Ingredient3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ingredient3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ingredient3ActionPerformed

    private void IngredientNum4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngredientNum4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngredientNum4ActionPerformed

    private void Ingredient4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ingredient4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ingredient4ActionPerformed

    private void Ingredient5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ingredient5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ingredient5ActionPerformed

    private void IngredientNum5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngredientNum5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngredientNum5ActionPerformed

    private void IngredientNum6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngredientNum6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngredientNum6ActionPerformed

    private void Ingredient6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ingredient6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ingredient6ActionPerformed

    private void multiplierTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplierTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_multiplierTextFieldActionPerformed

    private void multipleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multipleButtonActionPerformed
        convertedText.setText("");
        ArrayList<String> output = new ArrayList();
        String input = multiplierTextField.getText().trim();
        if (input.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a multiplier", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else if (!isNumeric(input)) {
            JOptionPane.showMessageDialog(this, "Please enter a valid numeric multiplier", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
                multiplier = Double.parseDouble(input);
                for(int i=0;i<ingreidentNums.size();i++){
                    if(ingreidentNums.get(i).getText().equals("")){
                        continue;
                    }
                    String measurment = ingreidentNums.get(i).getText();
                    int numericPart = Integer.valueOf(measurment.replaceAll("[^\\d.]", ""));
                    String unitPart = measurment.replaceAll("[\\d.]", "").trim();
                    output.add(String.valueOf(numericPart*multiplier)+unitPart+" "+ingreidentNames.get(i).getText());
                }
                for(String line : output){
                    convertedText.append(line+"\n");
                }
        }
    }//GEN-LAST:event_multipleButtonActionPerformed

    private void divideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideButtonActionPerformed
        convertedText.setText("");
        ArrayList<String> output = new ArrayList();
        String input = multiplierTextField.getText().trim();
        if (input.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a multiplier", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else if (!isNumeric(input)) {
            JOptionPane.showMessageDialog(this, "Please enter a valid numeric multiplier", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else if(input.equals("0")){
            JOptionPane.showMessageDialog(this, "Cannot Divide by 0", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        else {
                multiplier = Double.parseDouble(input);
                for(int i=0;i<ingreidentNums.size();i++){
                    if(ingreidentNums.get(i).getText().equals("")){
                        continue;
                    }
                    String measurment = ingreidentNums.get(i).getText();
                    int numericPart = Integer.valueOf(measurment.replaceAll("[^\\d.]", ""));
                    String unitPart = measurment.replaceAll("[\\d.]", "").trim();
                    output.add(String.valueOf(String.format("%.1f", numericPart/multiplier))+unitPart+" "+ingreidentNames.get(i).getText());
                }
                for(String line : output){
                    convertedText.append(line+"\n");
                }
        }
    }//GEN-LAST:event_divideButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        for(int i=0;i<ingreidentNums.size();i++){
            ingreidentNums.get(i).setText("");
            ingreidentNames.get(i).setText("");
        }
        multiplierTextField.setText("");
        convertedText.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed
    public void close(){
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
    
    public static boolean isNumeric(String str) {
    if (str == null || str.isEmpty()) {
        return false;
    }
    try {
        Double.parseDouble(str);
        return true;
    } catch (NumberFormatException e) {
        return false;
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecipeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecipeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecipeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecipeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecipeMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Ingredient;
    private javax.swing.JTextField Ingredient1;
    private javax.swing.JTextField Ingredient2;
    private javax.swing.JTextField Ingredient3;
    private javax.swing.JTextField Ingredient4;
    private javax.swing.JTextField Ingredient5;
    private javax.swing.JTextField Ingredient6;
    private javax.swing.JTextField IngredientNum;
    private javax.swing.JTextField IngredientNum1;
    private javax.swing.JTextField IngredientNum2;
    private javax.swing.JTextField IngredientNum3;
    private javax.swing.JTextField IngredientNum4;
    private javax.swing.JTextField IngredientNum5;
    private javax.swing.JTextField IngredientNum6;
    private javax.swing.JLabel Multipler;
    private javax.swing.JButton clearButton;
    private javax.swing.JTextArea convertedText;
    private javax.swing.JButton divideButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton multipleButton;
    private javax.swing.JTextField multiplierTextField;
    private javax.swing.JButton quitButton2;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
